config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'pages#home'

  # User and messaging routes
  resources :users, only:[:show] do
    resources :chats, only:[:index, :create, :show]
  end

  resources :messages, only:[:create]

  # Item routes
  get "item/new", to: "items#new", as: "new_item"
  post "items", to: "items#create"
  patch "items/:item_id", to: "items#update", as: :edit_item
  delete "items/:item_id", to: "items#destroy", as: :delete_item

  # Reservation routes

  post "item/:item_id/reservation", to: "reservations#create", as: "new_reservation"
  delete "reservation/:reservation_id", to: "reservations#destroy"
  patch "reservation/:reservation_id", to: "reservations#update", as: "update_reservation"



  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :reservations_made_on_other_items, class_name: "Reservation"
  has_many :reservations_on_own_items, through: :items, source: :reservations

  has_one_attached :profile_picture

  validates :username, presence: true, uniqueness: true

  # Geocode related
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  # Messaging related
  has_many :messages
  has_many :subscriptions
  has_many :chats, through: :subscriptions

  def existing_chats_users
    existing_chat_users = []
    self.chats.each do |chat|
    existing_chat_users.concat(chat.subscriptions.where.not(user_id: self.id).map { |subscription| subscription.user })
    end
    existing_chat_users.uniq
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.includes(:items, :reservations_made_on_other_items, :reservations_on_own_items).find(params[:id])
    authorize @user
  end
end

app/views/users/_form.html.erb
<%= simple_form_for(user, url: user_registration_path, html: { method: :put }) do |f| %>
<%= f.error_notification %>

<div class="form-inputs">
  <%= f.input :email, required: true, autofocus: true %>
  <%= f.input :username, required: true, autofocus: true%>
  <%= f.input :password, hint: "leave it blank if you don't want to change it", required: false, input_html: { autocomplete: "new-password" } %>
  <%= f.input :password_confirmation, required: false, input_html: { autocomplete: "new-password" } %>
  <%= f.input :address %>
  <%= f.file_field :profile_picture %>
</div>

<div class="form-actions">
  <%= f.button :submit, "Update" %>
</div>
<% end %>

app/views/users/_user_modal.html.erb
<div class="modal fade" id="exampleModal-<%= user.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <div class="col-md">
            <div class="input-group">
              <div class="input-group-addon"></div>
            </div>
          </div>
        </div>
        <%= render "users/form", user: user %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<hr>
<div class="container bootstrap snippet">

  <h1 class="p-5"><%= @user.username %></h1>
  <div class="row">

    <div class="col-sm-3">
      <div class="text-center">
        <% if @user.profile_picture.attached? %>
          <div class="avatar-profileimg">
            <a href="#"><%= image_tag url_for(@user.profile_picture), class:"card-img-top" %></a>
          </div>
        <% else %>
          <div class="avatar-profileimg">
            <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" alt="alt">
          </div>
        <% end%>

      </div>
      <div class="panel panel-default">
        <div class="panel-heading"></div>
      </div>
    </div>
    <div class="btn-container">
      <%=link_to "Message", user_chats_path(current_user, other_user: @user.id), method: :post, class: "btn standard-btn"%>
      <% if @user == current_user%>
        <%=link_to "Create Item", new_item_path, class: "btn standard-btn"%>
        <button type="button" class="btn standard-btn" data-toggle="modal" data-target="#exampleModal-<%= @user.id %>">
          <span>Edit Profile</span>
        </button>
      <% end %>
      <%= render "user_modal", user: @user %>
      <p class="p-5">Adress:
        <%= @user.address %></p>
    </div>

    <!-- enf of col-sm-3 -->

    <div class="col-sm-9">
      <% if @user == current_user%>
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#home">My products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#messages">My things rented</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#settings">Things I am renting</a>
          </li>
        </ul>

        <div class="tab-content">

          <div class="tab-pane active" id="home">
            <hr>
            <div class="d-flex flex-wrap">
              <% @user.items.each do |item| %>
                <%= render "items/item_card", item: item %>
                <%= render "items/item_modal", item: item %>
              <% end %>
            </div>
            <hr>
          </div>

          <div class="tab-pane" id="messages">
            <hr>
            <div class="inner-tabs-cards my-thing-rented">
              <% @user.reservations_on_own_items.each do |reservation|  %>
                <%= render "reservations/reservation_card", reservation: reservation %>
              <% end %>
            </div>
            <hr>
          </div>

          <div class="tab-pane" id="settings">
            <hr>
            <div class="d-flex flex-wrap">
              <% @user.reservations_made_on_other_items.each do |reservation|  %>
                <%= render "reservations/reservation_card", reservation: reservation %>
              <%end%>
            </div>
          </div>
        </div>
      <% else %>
        <div class="d-flex flex-wrap">
          <% @user.items.each do |item| %>
            <%= render "items/item_card", item: item %>
            <%= render "items/item_modal", item: item %>
          <% end %>
        </div>
      <%end%>
    </div>
  </div>
</div>
</div>