config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'pages#home'

  # User and messaging routes
  resources :users, only:[:show] do
    resources :chats, only:[:index, :create, :show]
  end

  resources :messages, only:[:create]

  # Item routes
  get "item/new", to: "items#new", as: "new_item"
  post "items", to: "items#create"
  patch "items/:item_id", to: "items#update", as: :edit_item
  delete "items/:item_id", to: "items#destroy", as: :delete_item

  # Reservation routes

  post "item/:item_id/reservation", to: "reservations#create", as: "new_reservation"
  delete "reservation/:reservation_id", to: "reservations#destroy"
  patch "reservation/:reservation_id", to: "reservations#update", as: "update_reservation"



  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="sticky">
<nav class="menu">
  <ol>
    <li class="img-logo">
      <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag("logo1.png", width: 30) %>
    <% end %>
  </li>
  <% if user_signed_in? %>
    <li class="menu-item"><%= link_to "Profile", user_path(current_user)%></li>
    <li class="menu-item">
      <%= link_to "Your messages", user_chats_path(current_user) %>
    </li>
    <li class="menu-item">
      <%= link_to "Log out", destroy_user_session_path, method: :delete %>
    </li>
  <% else %>
    <li class="menu-item"></li>
    <li class="menu-item">
      <%= link_to "SignUp", new_user_registration_path %>
    </li>
    <li class="menu-item">
      <%= link_to "LogIn", new_user_session_path %>
    </li>
    <% end %>
  </ol>
</nav>
</div>