config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'pages#home'

  # User and messaging routes
  resources :users, only:[:show] do
    resources :chats, only:[:index, :create, :show]
  end

  resources :messages, only:[:create]

  # Item routes
  get "item/new", to: "items#new", as: "new_item"
  post "items", to: "items#create"
  patch "items/:item_id", to: "items#update", as: :edit_item
  delete "items/:item_id", to: "items#destroy", as: :delete_item

  # Reservation routes

  post "item/:item_id/reservation", to: "reservations#create", as: "new_reservation"
  delete "reservation/:reservation_id", to: "reservations#destroy"
  patch "reservation/:reservation_id", to: "reservations#update", as: "update_reservation"



  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :item
  belongs_to :user

  validates :status, inclusion: ["Pending", "Accepted", "Rejected"]
  # validates :start_date, presence: true
  # validates :end_date, presence: true
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :destroy, :update]

  def create
    @reservation = Reservation.new(user: current_user)
    @reservation.item = Item.find(params[:item_id])
    authorize @reservation
    if @reservation.save
      flash[:notice] = "You'r renting a thing!"
      redirect_to user_path(current_user)
    else
      render "users/show"
    end
  end

  def update
    @reservation.status = "Accepted" if params[:status] == "accept"
    @reservation.status = "Rejected" if params[:status] == "reject"
    if @reservation.save
      flash[:notice] = "Reservation successfully updated"
    else
      flash[:alert] = "Something went wrong we could not update"
      render "users/show"
    end
  end

  def destroy
    if @reservation.destroy
      flash[:notice] = "Reservation successfully deleted"
      redirect_to user_path(current_user)
    else
      render "users/show"
    end
  end

  private

  def set_reservation
    @reservation = Reservation.find(params[:reservation_id])
    authorize @reservation
  end
end

app/views/reservations/_reservation_card.html.erb
<div id="<%=reservation.id %>" class="card" style="width: 50%;">
  <div class="card-body">
    <h5 class="card-title"><%= reservation.item.title %></h5>
    <% if reservation.user == current_user%>
      <%= link_to reservation.item.user.username, user_path(reservation.item.user)%>
    <% else %>
      <%= link_to reservation.user.username, user_path(reservation.user)%>
    <%end%>

    <p id="status-<%= reservation.id %>"><%= reservation.status %></p>
    <% if reservation.status == "Pending" && reservation.user != current_user %>
      <%= link_to "Accept", update_reservation_path(reservation, status: "accept"), method: :patch, remote: true, class: "btn btn-secondary", id: "accepted-#{reservation.id}" %>
      <%= link_to "Reject", update_reservation_path(reservation, status: "reject"), method: :patch, remote: true, class: "btn btn-secondary", id: "rejected-#{reservation.id}" %>
    <% end%>
  </div>
</div>

app/views/reservations/update.js.erb
function updateStatus(status) { const reservationStatus = document.getElementById("status-<%= @reservation.id %>"); reservationStatus.innerHTML = status; document.getElementById("accepted-<%= @reservation.id %>").remove(); document.getElementById("rejected-<%= @reservation.id %>").remove() }

<% unless @reservation.errors.any? %>
  updateStatus("<%= @reservation.status %>");
<% end %>