config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'pages#home'

  # User and messaging routes
  resources :users, only:[:show] do
    resources :chats, only:[:index, :create, :show]
  end

  resources :messages, only:[:create]

  # Item routes
  get "item/new", to: "items#new", as: "new_item"
  post "items", to: "items#create"
  patch "items/:item_id", to: "items#update", as: :edit_item
  delete "items/:item_id", to: "items#destroy", as: :delete_item

  # Reservation routes

  post "item/:item_id/reservation", to: "reservations#create", as: "new_reservation"
  delete "reservation/:reservation_id", to: "reservations#destroy"
  patch "reservation/:reservation_id", to: "reservations#update", as: "update_reservation"



  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :reservations, dependent: :destroy

  belongs_to :category
  belongs_to :user

  has_one_attached :image

  # validates :image, presence: true
  validates :title, presence: true, length: { in: 5..80 }
  validates :description, presence: true, length: { in: 30..400 }
  # validates :availability_date_start, presence: true
  # validates :availability_date_end, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:update, :destroy]

  def new
    @item = Item.new
    authorize @item
  end

  def create
    @item = Item.new(items_params)
    @item.user = current_user
    authorize @item
    if @item.save
      flash[:notice] = "Item successfully listed"
      redirect_to user_path(current_user)
    else
      flash[:alert] = "The item could not be listed"
      render :new
    end
  end

  def update
    if @item.update(items_params)
      flash[:notice] = "Item successfully updated"
      redirect_to user_path(current_user)
    else
      flash[:alert] = "Item could not be updated"
      render "users/show"
    end
  end

  def destroy
    if @item.destroy
      flash[:notice] = "Item successfully deleted"
      redirect_to user_path(current_user)
    else
      render "users/show"
    end
  end

  private

  def set_item
    @item = Item.find(params[:item_id])
    authorize @item
  end

  def items_params
    params.require(:item).permit(:title, :description, :image, :category_id, :user_id)
  end
end

app/views/items/_form.html.erb
<div class="form-inputs">
  <%= simple_form_for item , url: edit_item_path(item) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.association :category %>
  <%= f.file_field :image %>
  <%= f.submit value: "List your item" %>
<% end %>
</div>

app/views/items/_form_new.html.erb
<div class="form-inputs">
  <%= simple_form_for @item do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.association :category %>
  <%= f.file_field :image %>
</div>

<div class="form-actions">
  <%= f.button :submit, "List your item" %>
</div>
<% end %>

app/views/items/_info_window.html.erb
<% if item.image.attached? %>
  <%= image_tag url_for(item.image), class:"card-img-top" %>
<% end %>
<h2><%= item.title %></h2>
<p><%= item.description %></p>
<button>
  <%= link_to "Borrow a thing", new_reservation_path(item), method: :post, class: "btn btn-quatrery" %>
</button>

app/views/items/_item_card.html.erb
<div class="card category-<%=item.category.name.split.join('-')%> item" style="width: 100%;">
  <% if item.image.attached? %>
    <a href="#"><%= image_tag url_for(item.image), class:"card-img-top" %></a>
  <% else %>
    <img class="card-img-top" src="http://placehold.it/700x400" alt="">
  <% end%>
  <div class="card-user-avatar">
    <% if item.user.profile_picture.attached? %>
      <%= image_tag url_for(item.user.profile_picture), class:"card-img-top" %>
    <% else %>
      <img class="avatar dropdown-toggle" src="https://kitt.lewagon.com/placeholder/users/ssaunier" alt="Avatar"/>
    <% end%>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= item.title %></h5>
    <h6 class="categories-card"><%= item.category.name %></h6>
    <p class="card-text"><%= item.description %></p>
  </div>
  <% if item.user == current_user %>
    <div class="card-btn">
      <h3 type="button" class="btn btn-primaryy" data-toggle="modal" data-target="#exampleModal-<%= item.id %>">
        <span>Edit</span>
      </h3>
      <%= link_to "Delete", delete_item_path(item), method: :delete, class: "btn btn-secondary" %>
    </div>
  <% else %>
    <div class="card-btn">
      <%= link_to "Borrow a thing", new_reservation_path(item), method: :post, class: "btn btn-quatrery" %>
      <%= link_to "About #{item.user.username}", user_path(item.user), class: "btn btn-cinquery" %>
    </div>
  <% end %>
</div>

app/views/items/_item_modal.html.erb
<div class="modal fade" id="exampleModal-<%= item.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <div class="col-md">
            <div class="input-group">
              <div class="input-group-addon"></div>
            </div>
          </div>
        </div>
        <%= render "items/form", item: item %>
      </div>
    </div>
  </div>
</div>

app/views/items/_map.html.erb
<div class="map">
  <div id="map" style="width: 100%; height: 600px;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= Rails.application.credentials.dig(:mapbox, :api_key) %>"></div>
</div>

app/views/items/new.html.erb
<h1>Create a new Item</h1>
<br>
<%= render "form_new", item: @item %>